// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjgldqkpqowkkybqmzpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqZ2xkcWtwcW93a2t5YnFtenBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjc2NzIsImV4cCI6MjA3MTcwMzY3Mn0.igd1ButR0ysxJoGgRRuwCo5AgASSC6oavb2bAQUYQd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});